### PR TITLE
Added connection from the home page to surveyor

### PR DESCRIPTION
**Pull request by OmarAgamy9**

### CODE REVIEW

**Review by Dez1999 — CHANGES_REQUESTED** [review]
Looks good! However, one suggestion is to have the "createSurvey" link in the Surveyors Home Page containing the surveys. Then have a "surveyorHome" link instead in the "HomePage.html"

**Comment by OmarAgamy9** [comment]
> Looks good! However, one suggestion is to have the "createSurvey" link in the Surveyors Home Page containing the surveys. Then have a "surveyorHome" link instead in the "HomePage.html"

Will do so good suggestion!

**Comment by hassanidea** [comment]
Looks good to me

**Review by Dez1999 — APPROVED** [review]

**Review by hassanidea — APPROVED** [review]
Good job by connecting the add question wtih the mcq and open ended in the createsurvey page

**Pull request merged**
